---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: crdant/compliance-image
    tag: latest

inputs:
- name: source

outputs:
- name: compliance-documentation

run:
  path: source/ci/tasks/compliance-docs.sh
  args: [
    --input-dir, source,
    --output-dir, documents,
    --artifactId, hello-node,
    --packaging, tgz
  ]
