---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: opencontrolorg/compliance-masonry
    tag: latest

inputs:
- name: source
- name: version

outputs:
- name: documents

run:
  path: source/ci/tasks/compliance-docs.sh
  args: [
    --input-dir, source,
    --output-dir, documents,
    --artifactId, hello-node,
    --version-file, version/number,
    --packaging, tgz
  ]
