---
jobs:
  - name: build
    serial_groups: [ version ]
    plan:
      - get: source
        trigger: true
      - get: node-modules
      - get: version
        params: { pre: rc }
      - task: unit-test
        file: source/ci/tasks/unit.yml
      - task: install
        file: source/ci/tasks/install.yml
      - put: candidate-release
        params: { file: package/((application))-*.tgz }
      - put: version
        params: { file: version/number }

  - name: integration-test
    serial: true
    plan:
      - get: candidate-release
        trigger: true
        passed: [ build ]
      - get: source
        passed: [ build ]
      - get: node-modules
        passed: [ build ]
      - get: version
        passed: [ build ]
      - task: prepare
        file: source/ci/tasks/prepare-integration.yml
      - put: cf-integration
        params:
          manifest: prepared/manifest.yml
      - put: cf-integration-route
        params:
          create:
          - ((cf-integration-host)).((cf-integration-domain))
          map:
          - ((cf-integration-host)).((cf-integration-domain))
          application: ((application))
      - task: integration-test
        file: source/ci/tasks/integration.yml
        params:
          CF_HOST: ((cf-integration-host))
          CF_DOMAIN: ((cf-integration-domain))

  - name: scan-and-document
    serial: true
    plan:
      - get: candidate-release
        trigger: true
        passed: [ integration-test ]
      - get: source
        passed: [ integration-test ]
      - get: node-modules
        passed: [ integration-test ]
      - get: version
        passed: [ integration-test ]
      - task: compliance-docs
        file: source/ci/tasks/compliance-docs.yml
      - put: compliance-docs
        params:
          file: documents/((application))-compliance-*.tgz
      - put: code-analysis
        params:
          project_path: source
      - put: deliver-story
        params:
          repos:
          - source

  - name: ship-it
    serial_groups: [ version ]
    plan:
      - get: candidate-release
        passed: [ scan-and-document ]
      - get: source
        passed: [ scan-and-document ]
      - get: node-modules
        passed: [ scan-and-document ]
      - get: version
        params: { bump: final }
      - task: prepare
        file: source/ci/tasks/prepare-final.yml
      - task: release
        file: source/ci/tasks/release.yml
      - put: final-release
        params: { file: release/((application))-*.tgz }
      - put: cf-production-delete
        params:
          application: ((application))-venerable
      - put: cf-production-name
        params:
          current: ((application))
          new: ((application))-venerable
      - put: cf-production
        params:
          manifest: prepared/manifest.yml
      - put: cf-production-route
        params:
          create:
          - ((cf-production-host)).((cf-production-domain))
          map:
          - ((cf-production-host)).((cf-production-domain))
          - ((cf-production-host))-new.((cf-production-domain))
          application: ((application))
      - put: version
        params: { file: version/number }

  - name: validate-it
    serial_groups: [ version ]
    plan:
      - get: source
        passed: [ ship-it ]
      - get: node-modules
        passed: [ ship-it ]
      - get: final-release
        passed: [ ship-it ]
        trigger: true
      - get: version
        passed: [ ship-it ]
      - task: integration-test
        file: source/ci/tasks/integration.yml
        params:
          CF_HOST: ((cf-production-host))-new
          CF_DOMAIN: ((cf-integration-domain))
    on_failure:
      put: cf-production-route
      params:
        unmap:
          - ((cf-production-host)).((cf-production-domain))
        application: ((application))

  - name: cutover
    serial_groups: [ version ]
    plan:
      - get: final-release
        passed: [ validate-it ]
        trigger: true
      - put: cf-production-route
        params:
          unmap:
          - ((cf-production-host)).((cf-production-domain))
          application: ((application))-venerable
      - put: cf-production-route
        params:
          unmap:
          - ((cf-production-host))-new.((cf-production-domain))
          application: ((application))

  - name: rollback
    serial_groups: [ version ]
    plan:
      - get: final-release
        passed: [ validate-it ]
      - put: cf-production-route
        params:
          unmap:
          - ((cf-production-host)).((cf-production-domain))
          application: ((application))
      - put: cf-production-delete
        params:
          application: ((application))
      - put: cf-production-name
        params:
          current: ((application))-venerable
          new: ((application))

resources:
  - name: source
    type: git
    source: &app-source
      uri: ((github-uri))
      branch: ((github-branch))

  - name: node-modules
    type: npm-cache
    source:
      <<: *app-source
      paths:
        - package.json
        - .npmrc

  - name: version
    type: semver
    source:
      bucket: ((s3-bucket-version))
      initial_version: 1.0.0-rc.0
      key: current-version
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((s3-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: deliver-story
    type: tracker
    source:
      token: ((tracker-api-token))
      project_id: ((tracker-project-id))
      tracker_url: ((tracker-url))

  - name: candidate-release
    type: s3
    source:
      bucket: ((s3-bucket-release-candidates))
      regexp: ((application))-(.*).tgz
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((s3-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: compliance-docs
    type: s3
    source:
      bucket: ((s3-bucket-docs))
      regexp: ((application))-compliance-(.*).tgz
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((s3-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: cf-integration
    type: cf
    source: &cf-integration-source
      api: ((cf-integration-api))
      username: ((cf-integration-username))
      password: ((cf-integration-password))
      organization: ((cf-integration-org))
      space: "((cf-integration-space))"
      skip_cert_check: ((cf-integration-skip-cert))

  - name: cf-integration-route
    type: cf-route
    source:
      <<: *cf-integration-source

  - name: code-analysis
    type: sonar-runner
    source:
      host_url: https://sonarqube.example.com/
      login: 63a23c366e208d1d3fca72672afb814ac87ccd12
      project_key: io.crdant.hello-node
      branch: master

  - name: final-release
    type: s3
    source:
      bucket: ((s3-bucket-releases))
      regexp: ((application))-(.*).tgz
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key))
      region_name: ((s3-region))
      endpoint: ((s3-endpoint))
      sse-kms-key-id: ((s3-sse-kms-key-id))

  - name: cf-production
    type: cf
    source: &cf-production-source
      api: ((cf-production-api))
      username: ((cf-production-username))
      password: ((cf-production-password))
      organization: ((cf-production-org))
      space: "((cf-production-space))"
      skip_cert_check: ((cf-production-skip-cert))

  - name: cf-production-route
    type: cf-route
    source:
      <<: *cf-production-source

  - name: cf-production-name
    type: cf-rename
    source:
      <<: *cf-production-source

  - name: cf-production-delete
    type: cf-delete
    source:
      <<: *cf-production-source

resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource

  - name: cf-route
    type: docker-image
    source:
      repository: crdant/cf-route-resource

  - name: cf-rename
    type: docker-image
    source:
      repository: crdant/cf-rename-resource

  - name: cf-delete
    type: docker-image
    source:
      repository: crdant/cf-delete-resource

  - name: sonar-runner
    type: docker-image
    source:
      repository: cathive/concourse-sonarqube-resource
      tag: latest # For reproducible builds use a specific tag and don't rely on "latest".
